# Generated by Django 5.2.14 on 2026-05-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_exercise_duration_seconds_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientAvailability',
        ),
    ]
